# Generated by Django 4.1.13 on 2024-12-04 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veterinario', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'CitaMedica',
            },
        ),
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'Dueño',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamentos', models.TextField()),
                ('instrucciones', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='tratamientos/')),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='veterinariaApp.citamedica')),
            ],
            options={
                'db_table': 'Tratamiento',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='mascotas/')),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaApp.dueño')),
            ],
            options={
                'db_table': 'Mascota',
            },
        ),
        migrations.AddField(
            model_name='citamedica',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinariaApp.mascota'),
        ),
    ]
