# Generated by Django 4.1.13 on 2024-12-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='mascota',
            table=None,
        ),
    ]
