# Generated by Django 4.1.13 on 2024-12-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariaApp', '0002_alter_mascota_foto_alter_mascota_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citamedica',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='citamedica',
            table=None,
        ),
    ]
